//
//  constants.swift
//  MDI1-105-BookManager
//
//  Created by Christian Bonilla on 25/09/25.
//

import Foundation
import SwiftUICore

public let SETTINGS_THEME_KEY = "SETTINGS_THEME_KEY"
public let SETTINGS_ACCENT_COLOR_KEY = "SETTINGS_ACCENT_COLOR_KEY"
public let SETTINGS_ACCENT_COLOR_DEFAULT_VALUE = Color.blue
public let SETTINGS_GRID_COLUMNS_KEY = "SETTINGS_GRID_COLUMNS_KEY"
public let SETTINGS_GRID_COLUMNS_DEFAULT_VALUE = 2
public let SETTINGS_SHOW_RATING_KEY = "SETTINGS_SHOW_RATING_KEY"
public let SETTINGS_SHOW_RATING_DEFAULT_VALUE = true
public let SETTINGS_SHOW_LIST_GRID_KEY = "SETTINGS_SHOW_LIST_GRID_KEY"
public let SETTINGS_SHOW_LIST_GRID_DEFAULT_VALUE = false
